# Version 2 of the Docker Compose
# reference: https://docs.docker.com/compose/compose-file/
# cli reference: https://docs.docker.com/compose/reference/overview/
version: '2'
services:
  proxy:
    image: jekyll_proxy
    ports:
      - "127.0.0.1:80:80"
    links:
      - jekyll
    volumes:
#      - ./tmp-www/www:/var/www
      - ./ghome.vhost:/etc/nginx/sites-enabled/ghome.vhost
#      - ./tmp-www/logs/nginx/:/var/log/nginx
#      - ./nginx/default-configs/nginx.conf:/etc/nginx/nginx.conf
  jekyll:
    image: jekyll_jekyll
    environment:
      LANG: C.UTF-8
      TEST: "development"
    volumes:
      - ./../:/wip # development code location, should match working_dir
#    entrypoint:
#      - jekyll
#      - serve
#      - --host
#      - 0.0.0.0
#      - --config
#      - "_config.yml,_config.dev.yml"
    working_dir: /wip # this should match up to the volume

    entrypoint: /bin/sh
    command: -c "while true; do sleep 1; done" # Simple Daemon
